name: Binance CI

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

env:
  DOTNET_VERSION: 8.0.x
  PROJECT: ./src/RichillCapital.Binance/RichillCapital.Binance.csproj
  BUILD_CONFIGURATION: Debug
  ARTIFACT_DIRECTORY: ./artifacts

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build ${{ env.PROJECT }} -c ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Run tests
      run: |
        dotnet test ./tests/RichillCapital.Binance.UnitTests/RichillCapital.Binance.UnitTests.csproj -c ${{ env.BUILD_CONFIGURATION }} --no-restore --verbosity normal

    - name: Package artifact
      run: |
        dotnet pack ${{ env.PROJECT }} -c ${{ env.BUILD_CONFIGURATION }} -o ${{ env.ARTIFACT_DIRECTORY }} --no-restore --no-build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: RichillCapital.Binance-0.0.0-${{ env.BUILD_CONFIGURATION }}
        path: ${{ env.ARTIFACT_DIRECTORY }}     
  
  